import os
import shutil
import subprocess
from django.conf import settings
from django.core.files import File
from celery import shared_task
from .models import Project, Track

@shared_task
def process_audio_separation(project_id):
    """
    Executes actual Meta Demucs AI separation on a Project's primary track.
    Splits the uploaded stereo mix into 4 separate stems (Vocals, Drums, Bass, Other),
    saves them to Project tracks database, and cleans up temporary outputs.
    """
    print(f"[CELERY AI WORKER] 🚀 Starting AI separation for Project ID: {project_id}")
    
    try:
        project = Project.objects.get(id=project_id)
        
        # We separate the primary track uploaded (the complete mix)
        mix_track = project.tracks.first()
        if not mix_track:
            raise Exception("No input mix track found in project database.")
            
        if not mix_track.file or not os.path.exists(mix_track.file.path):
            raise Exception(f"Input audio file does not exist on disk path: {mix_track.file}")
            
        # Update Project status to Processing
        project.status = 'Processing'
        project.save()
        print(f"[CELERY AI WORKER] ⏳ Status set to Processing. Initiating Meta Demucs model CLI execution...")
        
        file_path = mix_track.file.path
        # Get filename without extension
        filename_without_ext = os.path.splitext(os.path.basename(file_path))[0]
        
        # Setup temporary directories under media/separated
        temp_output_dir = os.path.join(settings.MEDIA_ROOT, 'separated')
        os.makedirs(temp_output_dir, exist_ok=True)
        
        # Run Demucs CLI using Python's subprocess module
        # Passes: demucs -n htdemucs --mp3 -o <output_dir> <file_path>
        cmd = [
            "demucs",
            "-n",
            "htdemucs",
            "--mp3",
            "-o",
            temp_output_dir,
            file_path
        ]
        
        print(f"[CELERY AI WORKER] ⚡ Executing CLI: {' '.join(cmd)}")
        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True
        )
        print("[CELERY AI WORKER] 📺 Demucs output log completed successfully.")
        
        # Demucs places files inside: temp_output_dir/htdemucs/<filename_without_ext>/
        separated_dir = os.path.join(temp_output_dir, 'htdemucs', filename_without_ext)
        if not os.path.exists(separated_dir):
            raise Exception(f"Demucs execution did not generate expected stems folder at: {separated_dir}")
            
        # We parse the 4 standard output stems generated by the htdemucs model
        stems = ['vocals.mp3', 'drums.mp3', 'bass.mp3', 'other.mp3']
        
        for stem_file in stems:
            stem_path = os.path.join(separated_dir, stem_file)
            
            if os.path.exists(stem_path):
                # Format name nicely (e.g. "vocals.mp3" -> "Vocals")
                stem_name = os.path.splitext(stem_file)[0].title()
                
                print(f"[CELERY AI WORKER] 💾 Importing separated stem: {stem_name} ({stem_file})")
                
                # Save dynamically via Django Storage File interface
                with open(stem_path, 'rb') as f:
                    new_track = Track(project=project, name=stem_name)
                    # Copies stem into our permanent projects directory dynamically
                    new_track.file.save(stem_file, File(f), save=True)
            else:
                print(f"[CELERY AI WORKER] ⚠️ Warning: Expected stem file '{stem_file}' not found at {stem_path}")
                
        # Cleanup temporary files generated by Demucs to conserve server disk space
        shutil.rmtree(separated_dir, ignore_errors=True)
        print(f"[CELERY AI WORKER] 🧹 Temporary folder cleaned up.")
        
        # Complete the project background state
        project.status = 'Completed'
        project.save()
        print(f"[CELERY AI WORKER] 🎉 AI separation successfully completed for Project ID: {project_id}")
        
    except Project.DoesNotExist:
        print(f"[CELERY AI WORKER] ❌ Error: Project with ID {project_id} does not exist.")
    except Exception as e:
        print(f"[CELERY AI WORKER] ❌ Critical Error during Demucs execution: {str(e)}")
        try:
            # Fallback error status representation
            project = Project.objects.get(id=project_id)
            project.status = 'Failed'
            project.save()
        except Exception:
            pass
